# Generated by Django 6.1.1 on 2026-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectupdate_rewardtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='donation',
            name='cardholder_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar')], default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='donation',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='donation',
            name='gateway',
            field=models.CharField(default='mock', max_length=32),
        ),
        migrations.AddField(
            model_name='donation',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='current_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
