# Generated by Django 6.1.1 on 2026-09-12 17:06
"""
Backfill for the donation payment upgrade:

* Every donation that predates the gateway flow was a completed donation, so
  its status becomes 'successful'.
* Project.current_fund is re-derived from those (now) successful donations so
  the new denormalized column starts consistent with total_donations().
"""

from django.db import migrations
from django.db.models import Sum


def backfill_donation_status_and_fund(apps, schema_editor):
    Donation = apps.get_model('projects', 'Donation')
    Project = apps.get_model('projects', 'Project')

    Donation.objects.exclude(
        status__in=['successful', 'failed']
    ).update(status='successful', gateway='mock')

    project_ids = Donation.objects.values_list('project_id', flat=True).distinct()
    for project_id in project_ids:
        total = (
            Donation.objects.filter(project_id=project_id, status='successful')
            .aggregate(total=Sum('amount'))['total']
        )
        Project.objects.filter(pk=project_id).update(current_fund=total or 0)


def noop(apps, schema_editor):
    # Reversible migrations must provide a reverse; we keep the data as-is.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_donation_card_last4_donation_cardholder_name_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_donation_status_and_fund, noop),
    ]