# Generated by Django 6.1.1 on 2026-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_backfill_donation_status_and_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
